$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: PLACEHOLDER_DEPLOYMENT_NAME
endpoint_name: PLACEHOLDER_ENDPOINT_NAME
model: azureml:PLACEHOLDER_MODEL_NAME:PLACEHOLDER_MODEL_VERSION
instance_type: Standard_DS3_v2
instance_count: 1