model_name: churn_model
mlflow_run_id: b8dfb01f-d2f3-4192-a014-17ed954864f1
registered_model_name: ecom-churn_model
registered_model_version: '4'
features: order_count,avg_order_value,days_since_signup
target_column: churned
model_type: classifier
hyperparameters: '{"n_estimators": 200, "max_depth": 6}'
metric_name: roc_auc
min_threshold: 0.8
observed_metric_at_handoff: 0.9454868154158215
